In [32]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer

In [ ]:
import os

# Crear carpeta data si no existe
os.makedirs("data", exist_ok=True)

In [33]:
df = pd.read_csv('../data/creditcard.csv', sep=';', low_memory=False)

# Ver datos
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-13.598.071.336.738,-0.0727811733098497,253.634.673.796.914,137.815.522.427.443,-0.338320769942518,0.462387777762292,0.239598554061257,0.0986979012610507,0.363786969611213,...,-0.018306777944153,0.277837575558899,-0.110473910188767,0.0669280749146731,0.128539358273528,-0.189114843888824,0.133558376740387,-0.0210530534538215,149.62,0
1,0,119.185.711.131.486,0.26615071205963,0.16648011335321,0.448154078460911,0.0600176492822243,-0.0823608088155687,-0.0788029833323113,0.0851016549148104,-0.255425128109186,...,-0.225775248033138,-0.638671952771851,0.101288021253234,-0.339846475529127,0.167170404418143,0.125894532368176,-0.00898309914322813,0.0147241691924927,2.69,0
2,1,-135.835.406.159.823,-134.016.307.473.609,177.320.934.263.119,0.379779593034328,-0.503198133318193,180.049.938.079.263,0.791460956450422,0.247675786588991,-151.465.432.260.583,...,0.247998153469754,0.771679401917229,0.909412262347719,-0.689280956490685,-0.327641833735251,-0.139096571514147,-0.0553527940384261,-0.0597518405929204,378.66,0
3,1,-0.966271711572087,-0.185226008082898,179.299.333.957.872,-0.863291275036453,-0.0103088796030823,124.720.316.752.486,0.23760893977178,0.377435874652262,-138.702.406.270.197,...,-0.108300452035545,0.00527359678253453,-0.190320518742841,-117.557.533.186.321,0.647376034602038,-0.221928844458407,0.0627228487293033,0.0614576285006353,123.50,0
4,2,-115.823.309.349.523,0.877736754848451,1.548.717.846.511,0.403033933955121,-0.407193377311653,0.0959214624684256,0.592940745385545,-0.270532677192282,0.817739308235294,...,-0.00943069713232919,0.79827849458971,-0.137458079619063,0.141266983824769,-0.206009587619756,0.502292224181569,0.219422229513348,0.215153147499206,69.99,0

In [34]:
# Ver nombres de columnas
print(df.columns)

# Quitar espacios por si acaso
df.columns = df.columns.str.strip()

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [35]:
for col in df.columns:
    if col != 'Class':
        df[col] = df[col].astype(str).str.replace('.', '', regex=False)
        df[col] = pd.to_numeric(df[col], errors='coerce')

In [36]:
df.isnull().sum()

Time        1
V1          7
V2         21
V3         13
V4         15
V5         19
V6         28
V7         32
V8         73
V9         29
V10        38
V11        23
V12        36
V13        26
V14        29
V15        37
V16        22
V17        37
V18        22
V19        37
V20        74
V21        69
V22        28
V23       101
V24        79
V25        37
V26        36
V27       202
V28       237
Amount      0
Class       0
dtype: int64

In [37]:
X = df.drop('Class', axis=1)
y = df['Class']

print(X.shape, y.shape)

(284807, 30) (284807,)

In [38]:
imputer = SimpleImputer(strategy='mean')
X = imputer.fit_transform(X)

# Comprobar que no hay NaN
print(np.isnan(X).sum())

0

In [39]:
columnas = df.drop('Class', axis=1).columns

X_df = pd.DataFrame(X, columns=columnas)

y_df = pd.DataFrame(y, columns=['Class'])

df_clean = pd.concat([X_df, y_df], axis=1)

df_clean.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807e+13,-7.278117e+14,2.536347e+14,1.378155e+14,-3.383208e+14,4.623878e+14,2.395986e+14,9.869790e+14,3.637870e+14,...,-1.830678e+13,2.778376e+14,-1.104739e+14,6.692807e+14,1.285394e+14,-1.891148e+14,1.335584e+14,-2.105305e+14,14962.0,0
1,0.0,1.191857e+14,2.661507e+13,1.664801e+13,4.481541e+14,6.001765e+14,-8.236081e+14,-7.880298e+14,8.510165e+14,-2.554251e+14,...,-2.257752e+14,-6.386720e+14,1.012880e+14,-3.398465e+14,1.671704e+14,1.258945e+14,-8.983099e+14,1.472417e+14,269.0,0
2,1.0,-1.358354e+14,-1.340163e+14,1.773209e+14,3.797796e+14,-5.031981e+14,1.800499e+14,7.914610e+14,2.476758e+14,-1.514654e+14,...,2.479982e+14,7.716794e+14,9.094123e+14,-6.892810e+14,-3.276418e+14,-1.390966e+14,-5.535279e+14,-5.975184e+14,37866.0,0
3,1.0,-9.662717e+14,-1.852260e+14,1.792993e+14,-8.632913e+14,-1.030888e+14,1.247203e+14,2.376089e+13,3.774359e+14,-1.387024e+14,...,-1.083005e+14,5.273597e+14,-1.903205e+14,-1.175575e+14,6.473760e+14,-2.219288e+14,6.272285e+14,6.145763e+14,1235.0,0
4,2.0,-1.158233e+14,8.777368e+14,1.548718e+12,4.030339e+14,-4.071934e+14,9.592146e+14,5.929407e+14,-2.705327e+14,8.177393e+14,...,-9.430697e+14,7.982785e+13,-1.374581e+14,1.412670e+14,-2.060096e+14,5.022922e+14,2.194222e+14,2.151531e+14,6999.0,0

In [40]:
df_clean.isnull().sum().sum()

np.int64(0)

In [ ]:
df_clean.to_csv("data/creditcard_limpio.csv", index=False)